### PR TITLE
Blueprint to override default translation model to support dot notate…

### LINKED ISSUE #296: Add support for flat json structure
The current implementation does not seem to allow for flat-style keys.

Example:
```
{
    "login.authenticate": "Authenticate",
    "login.forgot-password": "Forgot Password"
}
```

It would be nice if ember-intl could detect this flat structure and parse them into something usable.
Currently, using a flat structure as per above causes Ember throw an error for not finding the parent key when it attempts to break it down:
```
Error: Property set failed: object in path "login" could not be found or was destroyed.
```

### PR DESCRIPTION
**Pull request by jasonmit**
…d translation keys

Fixes #296

### CODE REVIEW

File: packages/ember-intl/addon/adapters/default.js [hunk 1]
```diff
@@ -28,6 +26,7 @@ const DefaultIntlAdapter = Ember.Object.extend({
 
     const owner = getOwner(this);
     const lookupName = `ember-intl@translation:${normalize(localeName)}`;
+    const Translation = owner._lookupFactory('model:ember-intl-translation') || owner._lookupFactory('ember-intl@model:translation');
```
Comment (jasonmit) [inline packages/ember-intl/addon/adapters/default.js]: Tries to resolve from the app namespace first
